version: 2

# working Poetry solution from
# https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-1143587902
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install poetry==1.2.0
      - poetry config virtualenvs.create false
      - poetry install --with docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
